---

- name: install epel-release (CentOS)
  yum:
    name: epel-release
    state: present
    update_cache: yes

- block:

  - name: install iptables (CentOS 7)
    yum:
      name: iptables-services
      state: present
      update_cache: yes

  - name: disable firewalld
    service: name=firewalld state=stopped enabled=no

  - name: disable firewalld
    command: systemctl disable firewalld

  - name: mask firewalld
    command: systemctl mask firewalld

  - name: enable iptables
    command: systemctl enable iptables

  - name: enable ip6tables
    command: systemctl enable ip6tables

  when: ansible_distribution_major_version >= "7"
  tags:
    - install

- block:
  - name: Set custom iptalbes rules
    copy:
      src: "{{ custom_iptalbes_rules }}"
      dest: "/etc/sysconfig/iptables"
      owner: root
      group: root
      backup: yes
    when: custom_iptalbes_rules is defined

  - name: Set custom ip6tables rules
    copy:
      src: "{{ custom_ip6talbes_rules }}"
      dest: "/etc/sysconfig/ip6tables"
      owner: root
      group: root
      backup: yes
    when: custom_ip6talbes_rules is defined
  tags:
    - setup
