---


- block:
  - name: Copy custom iptalbes rules
    copy:
      src: "{{ custom_iptalbes_rules }}"
      dest: "/etc/iptables.firewall.rules"
      owner: root
      group: root
      backup: yes
    when: custom_iptalbes_rules is defined

  - name: Copy custom ip6tables rules
    copy:
      src: "{{ custom_ip6talbes_rules }}"
      dest: /etc/ip6tables.firewall.rules
      owner: root
      group: root
      backup: yes
    when: custom_ip6talbes_rules is defined

  - name: Set iptables-restore when server boot
    copy:
      src: iptables-restore
      dest: /etc/network/if-pre-up.d/firewall
      group: root
      owner: root
      mode: "o+x"
    when: ansible_virtualization_type != "docker"

  tags:
    - setup
